### ISSUE TITLE
Error during a cypress test

### ISSUE THREAD

**Issue by cyrilwseils** [EmmanuelDemey/eco-index-audit#117]
Hello,

When I try to use the checkEcoIndex method in a cypress test like your example, cypress returns an error that the method does not return a value.

"The task 'checkEcoIndex' returned undefined. You must return a value, null, or a promise that resolves to a value or null to indicate that the task was handled."

I got this in my cypress.config.js : 

```javascript
const { defineConfig } = require("cypress");
const { enableEcoIndexAuditForCypress } = require('eco-index-audit/src/cypress');

module.exports = defineConfig({
  chromeWebSecurity: false ,
  viewportWidth: 1440,
  viewportHeight: 1279,
  e2e: {
    setupNodeEvents(on) {
      on('task', {
        async checkEcoIndex(url){
          enableEcoIndexAuditForCypress(on, {
              beforeScript: (globals) => {
                localStorage.setItem('authorisation', global.accessToken)
              },
              afterScript: (globals) => {
                localStorage.clear()
              },
              headless: true,
          })
        }
      })
    },
  },
})
```

And my files  for test : 

```javascript
describe('Cypress test', () => {
  const url = 'https://google.com'
  beforeEach(() => {
    cy.visit(url)
  })

  it('should have a good ecoindex', () => {
    const threshold = 50
    cy.task("checkEcoIndex", { url }).its('ecoIndex', { timeout: 0 }).should('be.greaterThan', threshold);
  })
})
```

Thanks in advance for your help

**Comment by EmmanuelDemey** [comment]
Hi @cyrilwseils which version of Cypress are you using ?

**Comment by cyrilwseils** [comment]
Hi, i tested with a v10 and i updated to 12.7.0 to try but failed too

**Comment by EmmanuelDemey** [comment]
Hi @cyrilwseils 

I have just updated the README documentation : https://github.com/EmmanuelDemey/eco-index-audit#integration-with-cypress

Let me know if it works now.

**Comment by cyrilwseils** [comment]
Hi @EmmanuelDemey

**Comment by cyrilwseils** [comment]
Hi,

I tested and it work :) !
Thanks for the help !
